### ISSUE TITLE
when using pwman 0.3.0 on windows, no readline is found

### ISSUE THREAD

**Issue by oz123** [pwman3/pwman3#17]
O:\Python27\Scripts>python pwman3
Please enter your new password:
Please enter your new password again:
Error: global name 'readline' is not defined

**Comment by zQueal** [comment]
Having this issue as well:

```
λ pwman3
sqlite://C:/Users/{username}/.pwman/pwman.db
Please type in the master password:
Traceback (most recent call last):
  File "C:\Python27\Scripts\pwman3-script.py", line 9, in <module>
    load_entry_point('pwman3==0.7.1', 'console_scripts', 'pwman3')()
  File "C:\Python27\lib\site-packages\pwman3-0.7.1-py2.7.egg\pwman\ui\cli.py", line 110, in main
    cli = PwmanCli(db, xselpath, CLICallback, config)
  File "C:\Python27\lib\site-packages\pwman3-0.7.1-py2.7.egg\pwman\ui\cli.py", line 72, in __init__
    readline.read_history_file(self._historyfile)
NameError: global name 'readline' is not defined
```

**Comment by oz123** [comment]
@zQueal , 
I just did a commit with some fixes to this issue. I don't have a windows system at hand to test them. 
So I am counting on good fate here. Can you test if the current HEAD of `dev` branch works for you?

**Comment by zQueal** [comment]
@oz123 Working great now, thanks!

**Comment by oz123** [comment]
Great ! I happy to know there are more users for pwman3 out there! Please star it, so more people will know about it.
