### ISSUE TITLE
Corrupted database after database upgrade

### ISSUE THREAD

**Issue by donnm** [pwman3/pwman3#36]
I recently upgraded to 0.4.2 and upgraded the database using the -k parameter. After upgrading my password database is missing 3 entries (65 down from 68) and upon trying to print another one I receive an error message:

Error: could not convert string to int

This error is printed after the username field and returns to the prompt (the password is never displayed).

**Comment by oz123** [comment]
@donnm', Which version did you previously use?
Do you still have the old entries from 64 to 68? Please help me understand why the conversion failed after the 64th entry, maybe Unicode in notes? Or tags? 
Upon printing another one? What do you mean? Is this any node or a specific one that causes the problem?

**Comment by donnm** [comment]
I've done some more testing. I was wrong about the missing entries. I must have deleted a few of the entries at some point since the old database is missing those indices and the upgrade must have assigned new consecutive node numbers to them. A bit of string processing and a diff of the old and new lists confirms this.

However, out of 65 entries in total, 7 are corrupted so that I cannot retrieve the associated passwords. These are 40, 50, 52, 53, 55, 56, and 64. I use no special characters in the any of the fields, although some fields including username are left blank sometimes, although I can see no pattern between that and the corrupted entries. All corrupted entries are from index 40 onwards, so perhaps a recent version of pwman3 introduced the problem.

There are a variety of errors. For example the case I cited above:

pwman> print 52
Node 52.
Username: <redacted>
Error: could not convert string to int 
pwman> 

Another:

pwman> print 53
Node 53.
Username: <redacted>
Error:  
pwman> 

Yet another:

pwman> print 55
Node 55.
Username: <redacted>
Error: insecure string pickle 
pwman> 

Let me know if I can provide further information. If you tell me some way I can debug the database upgrade I will try that.

**Comment by oz123** [comment]
Hi @Donnm, 
Thanks again for bothering and researching this issue. I got to ask, why version 0.4.2? 
The 0.4.x branch is quite OLD, and since then there are multiple other version. Do you see this problem with 0.4.5 for example  0.5.3  versions ? 
How did you install pwam3? From a package or from pip ?

**Comment by donnm** [comment]
I will try a newer version. I installed it in trusty from ports.ubuntu.com. Previous version was 0.0.8-1 according to dpkg -s.

**Comment by donnm** [comment]
0.5 can't read the old nor the recently upgraded databases:

$ pwman3 
Error: no such table: CRYPTO 
$

$ pwman3 -d .pwman/pwman-newdb.db
Error: no such table: CRYPTO 
$

**Comment by oz123** [comment]
OK, 
I really hate to say this, but the 0.0.8 is so old I never thought of a direct upgrade path from it to 0.5.x. 
Your best chance is try all the old versions from 0.2 onwards. 

Are you installing from pip? from git? Which ubuntu version are you using?

**Comment by donnm** [comment]
I installed 0.5 from source with git and python setup.py install.

I'm using Ubuntu trusty 14.04.

If I go the pip way, is there an easy way to install older versions?

**Comment by oz123** [comment]
You can install directly from github releases:
Just do in your shell:

    $ sudo pip install https://github.com/pwman3/pwman3/archive/v0.2.0.tar.gz

See releases for other releases. If hope this version works for you.

**Comment by donnm** [comment]
I couldn't get that working, but using pip I installed 0.5.3 which prompted me to upgrade the old 0.0.8 database. After doing that everything is back to normal. Thanks for your help!

**Comment by oz123** [comment]
Yay! So there is something done right in pwman3! Don't get attached though to this version. I am currently working on 0.6 which is a complete re-write with a better encryption engine and many bug fixes. 
Since the old version is UTTERLY broken, there is no _direct_ way  to upgrade from 0.5 to 0.6. 
You'll have to export (see `help export` inside pwman3) and import your db when running 0.6.
