### ISSUE TITLE
Custom list formatting

### ISSUE THREAD

**Issue by kobaz** [pwman3/pwman3#37]
Personally I like my pwman output like this:
 name = "%s -- %s" % (n.url, n.username)

It would be really nice to read a format string from the config file so everyone can have their own preferred output

**Comment by oz123** [comment]
Indeed, this would be a nice feature to have. It should not be hard to implement a solution for this 
reading a string template from the configuration file. 
If this project is included it is even easier https://bitbucket.org/astanin/python-tabulate!

**Comment by daffcio** [comment]
XD

**Comment by oz123** [comment]
@kobaz it took a few years to get to this :-). I am sorry it took so long.
