### ISSUE TITLE
Password list sorting

### ISSUE THREAD

**Issue by kobaz** [pwman3/pwman3#38]
It would be great to have a sorted list (otherwise looking through a list of 500 passwords can be a bit time consuming to find what you want).

My own personal preference is sort on url... but it would be great to read this from the config file

nodes = sorted(nodes, key = lambda x: x.url)

**Comment by oz123** [comment]
Which version are you using? You don't need to scroll through 500 password. You can using 
```
pwman> ls <tag_name> 
```

This works in current master.

**Comment by kobaz** [comment]
I don't use tags and I prefer to search on url (when my terminal supports searching the scrollback buffer).  Ideally you could filter based on url or username as well.

**Comment by kobaz** [comment]
Version, I'm using 0.51d

**Comment by oz123** [comment]
This version is pretty old. Please give version 0.5.3 a try, and see if the functionality I describe does what you want. As for your other bug report, it's a nice feature, but it will take me some time to implement it.

**Comment by oz123** [comment]
@kobaz any feedback?

**Comment by kobaz** [comment]
Hey oz.. Sorry it's been a while.  0.5.1d is the latest in debian.  I need to figure out how to set it up from the package.  

Also... there's a new behavior in 0.5.1d different than what I'm used to... showing a password entry via the print command now auto clears the screen after a timeout.  This is a bit annoying as sometimes I need to go back and fourth between my app needing a password and pwman... and by the time i get back to it, the entry is gone.  So i've gotten into the habit of either hitting ctrl-c, or using the edit option to make sure the entry stays on the screen.

**Comment by kobaz** [comment]
Okay, so i git cloned the current master, rev of 07d712b

I'm getting the following error:
markm {~/download/pwman3} kobaz$ ~/.local/bin/pwman3 -c pwmanconfig
sqlite:///home/kobaz/.pwman/pwman.db
Error: no such table: CRYPTO

It looks like it's ignoring my config file... since the path to my pwman.db is not what it's printing out

**Comment by oz123** [comment]
@kobaz , versions 0.6 and further break compatability with previous versions. 
This is done in purpose, because the old code base was simpley too hard to maintain, and 
the database was simply used as a datastore for pickled python objects.

Further the current config file format is slightly changed. 

Please refer to the docs as for the correct way to specify the path to the file. 
If you would like to use your old database, you need to export it to CSV. 

See here:
http://pwman3.readthedocs.org/en/latest/install.html

**Comment by oz123** [comment]
@kobaz , did you have any success using newer versions of pwman3? 
Could you provide feedback? Is this ticket still relevant?

**Comment by oz123** [comment]
closing, since there is no answer from user.

**Comment by kobaz** [comment]
Reopening this old one!

It would be great to be able to have the output of 'ls' be sorted by URL.

Ideally this would be configurable.

**Comment by oz123** [comment]
Do you have to sort the urls alphabetically?

**Comment by kobaz** [comment]
Yes, that would be super useful!

Because the default sort (by-id) only shows you the list in the order it was inserted in.  If you wind up having 500 passwords like I do, it makes it difficult to find things since it's basically unordered...

**Comment by kobaz** [comment]
Filtering is useful, but I opened a separate issue for that.

**Comment by oz123** [comment]
@kobaz thanks for reporting the issue. I understand the problem. I don't mind pulling a PR. Please format the patches properly and I will happily merge them.

**Comment by kobaz** [comment]
Yeah I will be submitting patches...

Do you want patches for everything?  A lot of the changes are so small it was faster to write it out than to generate a patch.

**Comment by oz123** [comment]
see my comment about git. It's easy to generate patches with git, and if you already have a github a account it's even easier.
