### ISSUE TITLE
Error: Input strings must be a multiple of 16 in length

### ISSUE THREAD

**Issue by mabalew** [pwman3/pwman3#39]
Hi,

I'm using pwman3, 0.5.3 (installed via pip), tried 0.4.2-1 (default in my Linux distribution) and could not access my passwords, because of error mentioned in the title of the issue.
I think, it's pycrypto problem, but not sure, so wanna to know your opinion.

Regards,
Mariusz

**Comment by oz123** [comment]
@mabalew  did you upgrade your database from the old format?

What kind of encryption algorithm where you using? 

You probably can't go directly from 0.4.2 to 0.5.3. You should do incremental test 
the database with 0.4.3 and then export your database to CSV when using 0.5.x. 
After you have a CSV database you can import it again. 

You should also consider using 0.6 or 0.7 versions of pwman.

**Comment by mabalew** [comment]
Hi,

Thanks for the reply.
How could I check, what kind of encryption am I using?
0.4.2 was not working ("Input string must be a multiple..."), that's why I tried to upgrade.
How to make incremental test?
Versions 0.6 and 0.7 are also not working, the error, when I run it without parameters is:
sqlite:///home/mabalew/.pwman/pwman.db
Error: no such table: CRYPTO

When I run it like this: 
pwman-cli -c ~/.pwman/config -d ~/.pwman/pwman.db

I see:
Traceback (most recent call last):
  File "/usr/local/bin/pwman-cli", line 9, in <module>
    load_entry_point('pwman3==0.6', 'console_scripts', 'pwman-cli')()
  File "/usr/local/lib/python2.7/dist-packages/pwman/ui/cli.py", line 104, in main
    db = pwman.data.factory.createdb(dburi, dbver)
  File "/usr/local/lib/python2.7/dist-packages/pwman/data/factory.py", line 83, in createdb
    raise DatabaseException("Unknown database type specified")
pwman.data.database.DatabaseException: Unknown database type specified

I hope it helps to find the problem? I really, really need the passwords I stored in pwman for years...

**Comment by oz123** [comment]
@mabalew 

fear not. First, I don't think your database is corrupt. 
Your encryption type is specified in `~.pwman/config`. Please do `ls -l ~./pwman/`  and  post the output here. 

You can't use the new version of pwman3 with old databases. The documentation clearly says that.  
  
- Can you use your old pwman version with the that database?

(as a side note, do you have a back up copy of your database?)

**Comment by mabalew** [comment]
Encryption algorithm is AES

I just removed backup files from the list:
-rw-rw--w- 1 mabalew mabalew   171 maj 13 12:30 config
-rw------- 1 mabalew mabalew   841 maj 13 12:30 history
-rw-r----- 1 mabalew mabalew 19456 maj 13 12:01 pwman.db
-rw-r----- 1 mabalew mabalew  9216 kwi 24  2014 pwman-newdb.db

**Comment by oz123** [comment]
Are these backups readable? Or where they corrupt now ? 
Please try the following with pwman 0.5.3:

    pwman3 -d pwman-newdb.db

If this fails, edit the config file and change the algorithm to Blowfish (this was the default 
encryption in older versions of pwman3). And then try again with 

     pwman3 -d pwman-newdb.db

**Comment by mabalew** [comment]
Hi, Oz!

Change algorithm to Blowfish resolved my problem! Thank you, very much!!!

**Comment by oz123** [comment]
With which database `pwam-new.db`? Also,  now that you are using pwman 0.5.3 please use the export method to export your database to csv and upgrade to the latest pwman version.
