### ISSUE TITLE
Unicode Issue

### ISSUE THREAD

**Issue by JensHo** [pwman3/pwman3#45]
Testing latest version on a raspi before upgrade on my debian desktop, which has 0.5.1d (c).
Characters outside the "ascii range" can be entered and saved to the DB, but cause errors 
on output/display.

Cheers,

        Jens

jens@raspi1:~$ python --version
Python 2.7.3
jens@raspi1:~$ rm -rf .pwman/
jens@raspi1:~$ /usr/local/bin/pwman3 
sqlite:///home/jens/.pwman/pwman.db
Please type in the master password:
pwman3 0.8.0 (c) visit: http://pwman3.github.io/pwman3/
pwman>  n
Username: NameWithäUmlaut
Password (leave empty to create one):
Password length (default: 8):
Url: 
Notes: 
Tags: 
pwman> p 1
Traceback (most recent call last):
  File "/usr/local/bin/pwman3", line 9, in <module>
    load_entry_point('pwman3==0.8.0', 'console_scripts', 'pwman3')()
  File "/usr/local/lib/python2.7/dist-packages/pwman/ui/cli.py", line 126, in main
    cli.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/usr/local/lib/python2.7/dist-packages/pwman/ui/baseui.py", line 160, in do_p
    self.do_print(arg)
  File "/usr/local/lib/python2.7/dist-packages/pwman/ui/baseui.py", line 459, in do_print
    print(node)
  File "/usr/local/lib/python2.7/dist-packages/pwman/data/nodes.py", line 41, in __str__
    width=10, entry=str(self.username))
  File "/usr/local/lib/python2.7/dist-packages/pwman/data/nodes.py", line 100, in username
    return u.decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)

**Comment by oz123** [comment]
Hi Jens, 
Thank you for this report. This issue is solved with the current development branch. 
```

 $ pwman3 -d sqlite:////home/oznt/Software/test-bug-45.db
sqlite:////home/oznt/Software/test-bug-45.db
Please type in the master password:
pwman3 0.8.1 (c) visit: http://pwman3.github.io/pwman3/
pwman> n
Username: a näme with ümlaut ö
Password (leave empty to create one):
Password length (default: 8):
Url: example.org
Notes: 
Tags: foo
pwman> ls

ID  USER                     URL                      TAGS                
1   a näme with ümlaut ö     example.org              foo  
```

I am about to release version 0.9.0 from develop in a couple of days. You can install the current develop on your raspberry-pi if you want. 
Be advised, that this version has the following major changes
 
 - Drop support for Python2 (it's about time, and unicode is hard in Python2 but easier in Python3)
 - Replace PyCrypto with Cryptography
  - PyCrypto is dangerous and unmaintained. 
  - In theory, this should not stop you from reading your old Database. However, the underlying crypto algorithm used is AES with MODE_ECB, which can be insecure compared to MODE_CBC. 
  - Hence, with the usage of Cryptography the encryption is done with AES with MODE_CBC. Thus you will have to export your old pwman database to CSV and import it again to a new database. This process is easy and well documented. 


Thanks for the issue report! Vielen Dank, 
Oz

**Comment by JensHo** [comment]
Super, danke, Oz!
I came across this issue while trying to export/import for upgrading.

First time every I look into python, so I am very possibly missing something
when trying the latest dev branch:

`$ git clone https://github.com/pwman3/pwman3.git
Cloning into 'pwman3'...
remote: Counting objects: 6645, done.
remote: Compressing objects: 100% (163/163), done.
remote: Total 6645 (delta 103), reused 0 (delta 0), pack-reused 6481
Receiving objects: 100% (6645/6645), 1.31 MiB | 2.43 MiB/s, done.
Resolving deltas: 100% (4542/4542), done.
$ cd pwman3
$ python --version
Python 2.7.3
$ python setup.py install
.....
Installed /usr/local/lib/python2.7/dist-packages/pwman3-0.8.1-py2.7.egg
......
Finished processing dependencies for pwman3==0.8.1
$ pwman3 
sqlite:///home/jens/.pwman/pwman.db
Please type in the master password:
Error: 'EntryPoint' object has no attribute 'resolve' 
` 
Ok, no Python2 support anymore as mentioned.

`$ pip uninstall pwman3
Uninstalling pwman3:
  /usr/local/lib/python2.7/dist-packages/pwman3-0.8.1-py2.7.egg
Proceed (y/n)? y
  Successfully uninstalled pwman3
$ python3 --version
Python 3.2.3
$ python3 setup.py install
 File "setup.py", line 335
    Pwman3 supports MySQL, Postgresql and SQLite and even MongoDB"""
                                                                   ^
SyntaxError: invalid syntax
`
Deleted the unicode prefix in setup.py:330, not sure what the correct fix would be.
These don't look quite like followup errors from the above crude fix, but of course it could be from that:

`$ python3 setup.py install
........
byte-compiling build/bdist.linux-armv7l/egg/pwman/util/crypto/crypto_engine.py to crypto_engine.cpython-32.pyc
  File "build/bdist.linux-armv7l/egg/pwman/util/crypto/crypto_engine.py", line 261
    return self._salt.decode() + u'$6$' + self._digest.decode()
                                      ^
SyntaxError: invalid syntax
........
byte-compiling build/bdist.linux-armv7l/egg/pwman/util/crypto_engine.py to crypto_engine.cpython-32.pyc
  File "build/bdist.linux-armv7l/egg/pwman/util/crypto_engine.py", line 266
    return self._salt.decode() + u'$6$' + self._digest.decode()
                                      ^
SyntaxError: invalid syntax
........
Extracting pwman3-0.8.1-py3.2.egg to /usr/local/lib/python3.2/dist-packages
  File "/usr/local/lib/python3.2/dist-packages/pwman3-0.8.1-py3.2.egg/pwman/util/crypto_engine.py", line 266
    return self._salt.decode() + u'$6$' + self._digest.decode()
                                      ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.2/dist-packages/pwman3-0.8.1-py3.2.egg/pwman/util/crypto/crypto_engine.py", line 261
    return self._salt.decode() + u'$6$' + self._digest.decode()
                                      ^
SyntaxError: invalid syntax
`

Are you planning on updating the official debian repositories with this new version once it's out?

Grüße,

        Jens

**Comment by oz123** [comment]
Hi Jens, 

Strange errors... I am not seeing this on Python 3.4 and Python 3.5. But never the less I have a good guess where they come from, and I have made a commit which will prevent this module from being installed. 

Please update your repo (git pull) and then try again (you should install with  `sudo pip3 install .` rather then directly calling setup.py. Also, don't forget to  `sudo pip3 install cryptography`,

**Comment by oz123** [comment]
Regarding Debian, I can't promise the package will be updated. I will try and upload the package via mentors.debian.org.

With the release of pwman3 0.6 I gave notice for the package maintainer but I didn't get a response. You can also create a bug for that in Debian.

**Comment by JensHo** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=833678

**Comment by oz123** [comment]
+1. Did my did you succeed with installing from git as I suggested?

**Comment by JensHo** [comment]
I re-imaged the raspi with the latest image (minibian) from scratch, updated, installed 
all necessary packages, cloned from git and everything works just fine (install of 0.8.1, unicode).
There is no python2 anymore on it, and python3 is v3.4.2 now.

I was running install commands as root, just didn't document it - sorry for the confusion.

Thanks for all,

Jens
