### ISSUE TITLE
"Error: no such table: CRYPTO" after update

### ISSUE THREAD

**Issue by donnm** [pwman3/pwman3#51]
Pulled from git, updated with "python3 setup.py install" and get this error when I run pwman3 with no command line arguments: Error: no such table: CRYPTO

Last version I was running was 0.5.1d.

**Comment by oz123** [comment]
Yes, well you tried going from an old version 0.5.1, I couldn’t support so many backward versions. 
Glad you found a solution though .

**Comment by oz123** [comment]
http://pwman3.readthedocs.io/en/latest/install.html#upgrading-from-version-0-5-x
