### ISSUE TITLE
Delete entries without authenticating

### ISSUE THREAD

**Issue by donnm** [pwman3/pwman3#52]
Maybe this is intended behaviour, but it is possible to start pwman3 and delete a node without providing the password.

**Comment by oz123** [comment]
Oh... ah... no , that is a terrible thing. Really a stupid bug. 
Thanks for the report!!!

**Comment by oz123** [comment]
OK, I can confirm this issue. That is indeed not supposed to be like this.

**Comment by oz123** [comment]
This is fixed in 0.9.6
