### ISSUE TITLE
Config file option to disable screen flush

### ISSUE THREAD

**Issue by donnm** [pwman3/pwman3#54]
In the ancient 0.5 version I preferred the behaviour where I could just hit CTRL-L to flush the screen manually. That way it was easier to query for multiple passwords in a row without having to press Enter and have the screen cleared each time. Is it possible to add a config option to disable screen flush?

**Comment by oz123** [comment]
@donnm, I don't think it's going to be easy, and it does not make much sense to disable it.
What can be done, is to add an option to print multiple passwords.
E.g, change this behaviour:
```
pwman> p 99 91
print accepts only a single ID ...
``` 

does this help ?

**Comment by donnm** [comment]
I run pwman in GNU screen so it is rarely visible. Plus with GNU screen
you can scroll back and get around the screen flush anyway, so it not really a
security measure to rely on if someone gets access to your unlocked machine.

It's not useful to have a multiprint since I may not know apriori which
passwords I need.

If I have time I'll have a look and try to make a pull request.

My idea is to disable the flush screen if cls_timeout = 0, like it behaved
before, and just display the prompt again.

**Comment by oz123** [comment]
PRs are most welcome!

**Comment by oz123** [comment]
Oh, and yes, your idea is of course good too.

**Comment by oz123** [comment]
fix with #55  being merged
