### ISSUE TITLE
Upgraded pwman and can no longer use password database!

### ISSUE THREAD

**Issue by kobaz** [pwman3/pwman3#60]
pwman3env/bin/pwman3 -c /home/kobaz/notes/.pwman/config -d sqlite:///home/kobaz/notes/.pwman/pwman.db

sqlite:///home/kobaz/notes/.pwman/pwman.db
Error: no such table: CRYPTO

**Comment by oz123** [comment]
From which version you upgraded? The docs state you can't upgrade directly to the latest version.
Downgrade, export the database and import it to a newer version.

**Comment by kobaz** [comment]
Yeah I just found the information for upgrading. it took a while to find it.

I would suggest making a page on the wiki for upgrading... because many systems like debian ship old pwman3 (debian stretch uses 0.5.1d-1).

I'm sure other people will run into upgrade issues.

I managed to get this upgraded.

Also... switching topics.  Is there a way to filter passwords not by tag but by matching the username or url?

**Comment by kobaz** [comment]
Also, I used to use 'l' as a shortcut all the time, and now there's list and ls which are the same... What happened to the 'l' shortcut?

Thanks.

**Comment by oz123** [comment]
I'm willing to updated the package on Debian but I'm not using Debian myself and the maintainer of the package has not been answering my emails. Can you please open a bug in Debian? 


Why was it hard to find the warning about the upgrade? There are explicit sections about this you can even see the titles in here:
https://pwman3.readthedocs.io/en/latest/
I'm mentioning this because I don't want to maintain documentation in the wiki system to. 
I thought the link to the docs true the readme is quite clear.

**Comment by kobaz** [comment]
Right, agreed that the readthedocs.io link does have the information... but!

Humans tend to be lazy, programers are human (mostly)... myself included.  And the easier you make it for people, the less likely you'll get a dumb post from someone like me who didn't read all the material.

Here's what happened:
I cloned the git repo, installed and set up pwman3, and then ran it and said 'uh oh' when it couldn't load my password database.  I then I checked my command line args and verified that, I double checked my config file... I saw the error was a missing table, and for the heck of it I tried to use sqlite3 to load the database and create the needed table.

I found out of course that this table needs specific data, so my ad-hoc attempt at creating it did not work.  I then started looking for instructions if there were specific upgrade needs, so I found the README file but did not immediately look at the documentation link, because I assumed (wrongly) that all the critical/important information would be in the README, especially for breaking changes like database encryption.

I searched the github checkout for any upgrade instructions and could not find any. I then googled the exact error message about the missing table, and didn't find anything.  I went back to the pwman3 git hub and started poking around, and found the readthedocs.io page from the Documentation section on the main github page for pwman3.

I finally did find the upgrade instructions but it's only on the url.  I would highly recommend that at least a cursory warning in the README is in place for people upgrading.  It's common practice to include information about breaking changes in the README or in an UPGRADE file, and at least make mention of the new process in the CHANGELOG.

**Comment by kobaz** [comment]
Also... for upgrading the debian package, there should be a clear and simple upgrade path.   The normal debian upgrade process will *replace* the package you are upgrading... so somehow people will need to be warned that their data will no longer be accessible if they proceed with an upgrade prior to exporting.

I think ideally the pre-rm script for debian pwman3 would need to confirm that you've exported your password databases prior to completely removing the package.  It would be difficult to automate the export/import because anyone can have any kind of password db anywhere and there is guarantee everyone has theirs in a standard place.

 Probably need to discuss with some debian package maintainers (I am not one) on the best practices for this.

**Comment by oz123** [comment]
Thanks for the detailed answered. 
The information in read the docs is found in the git repo too. But I don't mind having it in the readme too. I think the readme is more for new comers, not for upgrading users.
As for the Debian problem, the package should probably spit a warning.
Problem is that your case is really old. 
Newer versions of pwman3 notify users on upgrades and in the case breaking changes will be introduced pwman3 will handle them better.

**Comment by oz123** [comment]
I'm closing this issue. The upgraded package was EXTREMELY old. All new version guarantee a smooth update. Users of versions 0.6 and older can export the DB to CSV and re-import it. No data los is caused.
