### ISSUE TITLE
New Feature: Search passwords by url

### ISSUE THREAD

**Issue by kobaz** [pwman3/pwman3#64]
The filter option for keywords is nice for specifc keywords, but sometimes I don't remember the exact keyword of an entry and I would just like to search on a filter of the url.

This would make using pwman3 exceptionally better when on mobile to avoid scrolling hundreds of entries to find the password entry.

Thanks!

**Comment by oz123** [comment]
This isn't so easy to implement, for this to happen one would probably need to save the URLs in clear text in database.
I think it's better to serach using the terminal. Modern terminals like gnome, mate xfce kde and some others all support searching text backwards.
I realize this answer might be a terrible one if you are using a brile terminal (I don't know if they support searching).

**Comment by kobaz** [comment]
Url would not have to be clear text.  'ls' has to pull the entire list of nodes from the DB anyway... so you now have the list... just post-filter the list in the display-loop.

**Comment by kobaz** [comment]
I'm going to start making patch files for future changes... they are no longer little one-liners!

But anyway.... I wrote a url filter.... I really don't know python so there may be some adjustments to be made but it works!

usage:
list/ls u:<url_filter>

this will list only nodes that contain a basic string match of <url_filter>

    def do_list(self, args):
        """
        list all existing nodes in database
        """
        url_filter = ""

        m = re.search('^u:(.*)$', args)
        if m:
          url_filter = m.group(1)

        rows, cols = self._prep_term()
        nodeids = self._get_node_ids(args)
        raw_nodes = self._db.getnodes(nodeids)
        _nodes_inst = self._db_entries_to_nodes(raw_nodes)
        head = self._format_line(cols - 10)
        print(tools.typeset(head, Fore.YELLOW, False))
        for idx, node in enumerate(_nodes_inst):
          self._print_node_line(node, rows, cols, url_filter)

    def _print_node_line(self, node, rows, cols, url_filter):
        if (url_filter != "" and node.url.find(url_filter) == -1):
          return

        tagstring = ','.join([t.decode() for t in node.tags])
        fmt = self._format_line(cols, node._id, node.username,
                                node.url[:50] + '...' if (len(node.url) > 50)
                                else node.url,
                                tagstring)
        formatted_entry = tools.typeset(fmt, Fore.YELLOW, False)
        print(formatted_entry)

There's a little more work to do, because it doesn't properly support searching on both url and tags, but that would just be a few lines.

**Comment by kobaz** [comment]
Okay, I fixed it up so it also will pass through tag searches

Now you can do this:

ls u:github.com kobaz

This will find urls matching github.com and the tag kobaz

    def do_list(self, args):
        """
        list all existing nodes in database
        """
        url_filter = ""

        m = re.search('^u:([^ ]+) ?(.*)$', args)
        if m:
          url_filter = m.group(1)
          args       = m.group(2)

        rows, cols = self._prep_term()
        nodeids = self._get_node_ids(args)
        raw_nodes = self._db.getnodes(nodeids)
        _nodes_inst = self._db_entries_to_nodes(raw_nodes)
        head = self._format_line(cols - 10)
        print(tools.typeset(head, Fore.YELLOW, False))
        for idx, node in enumerate(_nodes_inst):
          self._print_node_line(node, rows, cols, url_filter)

**Comment by kobaz** [comment]
This will seriously save me so much time!  I use pwman3 via ssh from my phone somewhat frequently, and my terminal app does not have any kind of search... and even if it did, with the small screen having to visually/manually deal with fewer lines is way better!
