### ISSUE TITLE
UI line_format not working

### ISSUE THREAD

**Issue by kobaz** [pwman3/pwman3#70]
Hi!

Thanks for all the improvements.  Especially merging in my search option for url, definitely handy.

Having an issue with line_format.  I'm playing with a modified example

.pwman/config

Adding:
[UI]
line_format = {ID:<3} {URL:<{url_pad}} -- {USER:<{user_pad}} Tags: {Tags:<{tag_pad}}

It doesn't seem to be using this at all, the line_format is still the default.

Also, I'm having some trouble finding documentation on the options for line_format.  For example, which variables and options are available.

**Comment by oz123** [comment]
See docs here: https://pwman3.readthedocs.io/en/latest/pwman.util.html#pwman.util.config.Config
