### ISSUE TITLE
Require master password  once

### ISSUE THREAD

**Issue by kobaz** [pwman3/pwman3#71]
HI,

Another feature that would be nice to have is an option in the config to only require the master password once like it used to.

The timeouts are a bit of a bummer to always have to retype my password on my home machine that no one uses but me.

**Comment by oz123** [comment]
Just set the time to a very long integer or minus 1.

**Comment by oz123** [comment]
Closing. No response from the OP.

**Comment by kobaz** [comment]
Hi,

This does not work.

lock_timeout = 600
cls_timeout = -1
cp_timeout = -1

Still asks for a password after a short timeout

**Comment by oz123** [comment]
OK, I will look into it.

**Comment by oz123** [comment]
@kobaz can you test if this fixes the issue for you?

**Comment by kobaz** [comment]
I can check this.  Thanks!

**Comment by kobaz** [comment]
I'm trying pwman3 master
$ python setup.py install
  File "setup.py", line 299
    return f".SH CONFIGURATION\n..{prefix}\n{body}\n"
                                                    ^
SyntaxError: invalid syntax

Looks like an error on line 299.

I changed
return f".SH CONFIGURATION\n..{prefix}\n{body}\n"
to
return ".SH CONFIGURATION\n..{prefix}\n{body}\n"

And there's still another issue after the above fix.
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 390, in <module>
    import pwman
  File "/home/kobaz/download/pwman3/pwman/__init__.py", line 22, in <module>
    import urllib.request
ImportError: No module named request


I'm going to try the develop branch

**Comment by kobaz** [comment]
The develop branch has the same problem.

**Comment by oz123** [comment]
Which Python version are you using? f-strings are only supported in Python3.6 or later.

**Comment by kobaz** [comment]
Ah... I don't really know python.  Got it.

Tried with python3 and this is now installing.

Trying out the password expiration now!

Thanks.

**Comment by oz123** [comment]
Well, which Linux distro are you using?

**Comment by kobaz** [comment]
Debian Buster

**Comment by oz123** [comment]
It's probably got bot Python2 and Python3. I hope the fix works for you.

**Comment by kobaz** [comment]
Seems like it's working.

lock_timeout = -1
cls_timeout = -1
cp_timeout = -1

**Comment by oz123** [comment]
You need to set lock_timeout = 600 , this will lock after 10 minutes for example. 
Can you describe what is not working?

**Comment by kobaz** [comment]
Oh... I want to completely disable the timeout for my home machine.  No one uses it but me, so one password to start is just fine.

and awwwwww. I thought the timeout was disabled, but at -1... I left my pc for 1 hour and now it's locked again

**Comment by oz123** [comment]
Have you tried the latest dev branch?

**Comment by kobaz** [comment]
This looks like it's working

**Comment by oz123** [comment]
Officially fixed in v0.12.2
