### ISSUE TITLE
MariaDB Support?

### ISSUE THREAD

**Issue by robertsilen** [pwman3/pwman3#93]
Hello, I see the README mentions MySQL and the [installation instructions](https://pwman3.readthedocs.io/en/latest/install.html), mention that pwman3 has been tested for MySQL 5.5. Does that mean MariaDB too? Could MariaDB be added, or any reason not to?

**Comment by oz123** [comment]
Hi, 

Maria DB should work out of the box. Pwman3 uses only basic features of MySQL, so I think it, it should also work with mariedb. The tests run against mysql only.
(And TBH, I only use sqlite3).

**Comment by robertsilen** [comment]
> Hi,
> 
> Maria DB should work out of the box. Pwman3 uses only basic features of MySQL, so I think it, it should also work with mariedb. The tests run against mysql only. (And TBH, I only use sqlite3).

Hello, thank you for your reply. I hope the update to add MariaDB in this PR is suitable? https://github.com/pwman3/pwman3/pull/94

**Comment by oz123** [comment]
Yes. Please add a test for MariaDB. I think it's not going to be hard. Look at the docker compose for a start. Finally add a test config to connect to MariaDBm

**Comment by robertsilen** [comment]
> Maria DB should work out of the box. Pwman3 uses only basic features of MySQL, so I think it, it should also work with mariedb. The tests run against mysql only. (And TBH, I only use sqlite3).

Indeed. As an extra comment: pwman3 has been running MariaDB in Debian since 2017 and on Fedora since 2015 (if I remember correctly). If you are not getting bug reports from Debian/Fedora users, then pwman3 probably does not have any particular issues with MariaDB.

**Comment by oz123** [comment]
Well, the test suite shows otherwise currently.
I no longer use Debian so I don't know if there is a package. If there is no package how would I get bug reports? Also, the user base can be very small and not necessarily interested in reporting bugs. 
After all this takes effort.
I will do my best to fix the issue with MariaDB very soon.
